-- Drop referencing tables
DROP TABLE IF EXISTS PlaylistSong;
DROP TABLE IF EXISTS BelongsTo;
DROP TABLE IF EXISTS ArtistLeaderboard;
DROP TABLE IF EXISTS GlobalLeaderboard;

-- Drop referenced tables
DROP TABLE IF EXISTS Song;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Playlist;
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS [User];
DROP TABLE IF EXISTS Leaderboard;

-- Create tables
CREATE TABLE Artist (
  ID INT NOT NULL IDENTITY(1,1),
  ArtistName VARCHAR(255) NOT NULL,
  Streams INT DEFAULT 0,
  PRIMARY KEY(ID)
);

CREATE TABLE [User] (
  ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Username VARCHAR(255)
);

CREATE TABLE Playlist (
  ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  TotalDuration INT DEFAULT 0,
  Genre VARCHAR(255),
  Visibility BIT,
  Name VARCHAR(255),
  AuthorID INT NOT NULL,
  FOREIGN KEY (AuthorID) REFERENCES [User](ID)
);

CREATE TABLE Album (
  ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Name VARCHAR(255),
  ReleaseDate DATE,
  TotalDuration INT DEFAULT 0,
  ArtistID INT NOT NULL,
  CoverImage VARBINARY(MAX),
  FOREIGN KEY (ArtistID) REFERENCES Artist(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Song (
  ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  ArtistID INT NOT NULL,
  Streams INT,
  Genre VARCHAR(255),
  Duration INT,
  Lyrics TEXT,
  Name VARCHAR(255),
  ReleaseDate DATE,
  AlbumID INT,
  FOREIGN KEY (ArtistID) REFERENCES Artist(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (AlbumID) REFERENCES Album(ID) --ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE PlaylistSong (
    PlaylistID INT NOT NULL,
    SongID INT NOT NULL,
    PRIMARY KEY (PlaylistID, SongID),
    FOREIGN KEY (PlaylistID) REFERENCES Playlist(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (SongID) REFERENCES Song(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BelongsTo (
  LeaderID INT NOT NULL,
  SongID INT NOT NULL,
  PRIMARY KEY (LeaderID, SongID),
  FOREIGN KEY (LeaderID) REFERENCES [User](ID),
  FOREIGN KEY (SongID) REFERENCES Song(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Leaderboard (
  LeaderID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Size INT
);

CREATE TABLE ArtistLeaderboard (
  LeaderID INT NOT NULL,
  ID INT NOT NULL,
  AuthorID INT NOT NULL,
  ArtistName VARCHAR(255) NOT NULL, --apagar o artist name e id ??
  PRIMARY KEY (LeaderID, ID),
  FOREIGN KEY (LeaderID) REFERENCES Leaderboard(LeaderID),
  FOREIGN KEY (AuthorID) REFERENCES Artist(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE GlobalLeaderboard ( --this is the songs leaderboard
  LeaderID INT NOT NULL,
  FOREIGN KEY (LeaderID) REFERENCES Leaderboard(LeaderID)
);;